---
kubectl_version: "1.11.0"
k8s_apiserver_secure_port: "6443"
k8s_ca_conf_directory: "{{ '~/k8s/certs' | expanduser }}"
k8s_config_directory: "{{ '~/k8s/configs' | expanduser }}"
k8s_ca_certificate_owner: "root"
k8s_ca_certificate_group: "root"
k8s_config_cluster_name: banditlair.com
k8s_encryption_config_directory: "{{k8s_config_directory}}"
