---
kube_network_plugin: weave
bin_dir: /usr/local/bin
kube_config_dir: /etc/kubernetes

kubelet_status_update_frequency: 4s
kube_controller_node_monitor_grace_period: 20s
kube_controller_node_monitor_period: 2s
kube_controller_pod_eviction_timeout: 30s


upstream_dns_servers:
  - 213.133.98.98
  - 213.133.99.99

kube_api_anonymous_auth: true
cert_manager_enabled: true
ingress_nginx_enabled: true
dashboard_enabled: false
helm_enabled: false
metrics_server_enabled: true
enable_nodelocaldns: true
docker_dns_servers_strict: false
