---
ip: "{{vpn_ip}}"
kube_network_plugin: flannel
bin_dir: /usr/local/bin
kube_config_dir: "/etc/kubernetes"

upstream_dns_servers: 
  - 195.20.55.180

#Addons
kube_api_anonymous_auth: true
metrics_server_enabled: true
