---
ip: "{{vpn_ip}}"
kube_network_plugin: flannel
bin_dir: /usr/local/bin
kube_config_dir: "/etc/kubernetes"

kube_api_anonymous_auth: true
ingress_nginx_enabled: true
ingress_nginx_host_network: true
ingress_nginx_nodeselector:
  node-role.kubernetes.io/node: ""
cert_manager_enabled: true