---
ansible_user: deploy
ansible_become: true
ansible_port: 22

harden_linux_sshd_settings_user:
  "^Port ": "Port 22"
harden_linux_ufw_rules:
  - rule: "allow"
    to_port: "22"
    protocol: "tcp"
  - rule: "allow"
    to_port: "7000"
    protocol: "udp"
docker_version: "17.03.2-ce"

