---
ansible_user: deploy
ansible_become: true
ansible_port: 2242

harden_linux_sshd_settings_user:
  "^Port ": "Port 2242"
harden_linux_ufw_rules:
  - rule: "allow"
    to_port: "2242"
    protocol: "tcp"
  - rule: "allow"
    to_port: "7000"
    protocol: "udp"
docker_version: "17.03.2-ce"

