---
- name: Create scripts
  template:
    src: "{{ item }}"
    dest: /root/{{ item }}
    mode: 0700
  loop:
    - dockerComposeAll.sh
    - syncData.sh
    - updateAll.sh

- name: Create syncDataToK8s.sh
  copy:
    src: syncDataToK8s.sh
    dest: /root/syncDataToK8s.sh
    mode: 0700

