version: '2.2'

networks:
  web:
    external:
      name: web

services:
  plex:
    image: plexinc/pms-docker:plexpass
    hostname: ${PLEX_DOMAIN}
    volumes:
      - /var/lib/plex/database:/config
      - /media:/data
      - /var/lib/plex/transcode:/transcode
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ADVERTISE_IP=https://plex.banditlair.com/
    labels:
      - "traefik.backend=plex"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:plex.banditlair.com"
      - "traefik.enable=true"
      - "traefik.port=32400"
      - "traefik.default.protocol=http"
    networks:
      - web
    restart: always
