---
- name: Copy emby config
  copy:
    src: emby
    dest: "{{docker_compose_files_folder}}"
- name: Start emby docker project
  docker_compose:
    project_src: "{{docker_compose_files_folder}}/emby"
    state: present
