- name: Anderia wiki deployment
  k8s:
    namespace: default
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: anderia-wiki
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: anderia-wiki
        template:
          metadata:
            labels:
              app: anderia-wiki
          spec:
            containers:
              - name: anderia-wiki
                image: bitnami/dokuwiki
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 80
                livenessProbe:
                  httpGet:
                    path: /
                    port: 80
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
                volumeMounts:
                - mountPath: "/bitnami"
                  name: anderia-wiki-data
            volumes:
              - name: anderia-wiki-data
                flexVolume:
                  driver: ceph.rook.io/rook
                  fsType: ceph
                  options:
                    fsName: ceph-fs # name of the filesystem specified in the filesystem CRD.
                    clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed

- name: Anderia wiki service
  k8s:
    namespace: default
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: anderia-wiki
      spec:
        type: ClusterIP
        ports:
          - port: 80
            targetPort: 80
        selector:
          app: anderia-wiki

- name: Anderia wiki ingress
  k8s:
    namespace: default
    state: present
    definition:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: anderia
        annotations:
          kubernetes.io/ingress.class: nginx
          certmanager.k8s.io/cluster-issuer: "{{cert_manager_issuer}}"
          # ingress.kubernetes.io/ssl-redirect: "true"
          # ingress.kubernetes.io/ssl-temporary-redirect: "false"
      spec:
        rules:
        - host: "{{ anderia_domain }}"
          http:
            paths:
            - path: /
              backend:
                serviceName: anderia-wiki
                servicePort: 80
        tls:
        - hosts:
            - "{{ anderia_domain }}"
          secretName: anderia-cert
