---
- name: Install monit
  package: name=monit state=present update_cache=yes
- name: Enable and start monit service
  systemd:
    name: monit.service
    state: started
    enabled: True
- name: Create fullBackup.sh
  copy:
    src: checkBackupStatus.sh
    dest: /usr/local/bin/checkBackupStatus.sh
    mode: 0700
- name: Copy monit config
  template:
    src: monitrc
    dest: /etc/monitrc
  notify:
      - reload monit
