---
- name: Copy searx config
  copy:
    src: searx
    dest: "{{docker_compose_files_folder}}"

- name: Start searx docker project
  docker_compose:
    project_src: "{{docker_compose_files_folder}}/searx"
    state: present
