version: '2.2'

networks:
  web:
    external:
      name: web

services:
  rpg_wiki:
    image: 'bitnami/dokuwiki:0.20170219.201708232029-r7'
    expose:
      - 80
    volumes:
      - '/var/lib/wiki/rpg:/bitnami'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=rpg_wiki"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:rpg.banditlair.com"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    networks:
      - web
    restart: always
