version: '2.2'

networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  rpg_wiki:
    image: 'bitnami/dokuwiki:latest'
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=rpg.banditlair.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
    volumes:
      - '/var/lib/wiki/rpg:/bitnami'
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-tier
    restart: always
