version: '2.2'

networks:
  web:
    external:
      name: web

services:
  anderia:
    image: 'bitnami/dokuwiki:0.20180422.201901061035'
    expose:
      - 80
    volumes:
      - '/var/lib/wiki/anderia:/bitnami'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=anderia"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:anderia.banditlair.com"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    networks:
      - web
    restart: always
  arkadia:
    image: 'bitnami/dokuwiki:0.20180422.201901061035'
    expose:
      - 80
    volumes:
      - '/var/lib/wiki/arkadia:/bitnami'
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=arkadia"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:arkadia.banditlair.com"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    networks:
      - web
    restart: always
