---
- name: Copy traefik config
  copy: src=traefik dest={{docker_compose_files_folder}}
- name: Create traefik .env
  template:
    src: traefik/.env
    dest: "{{docker_compose_files_folder}}/traefik/.env"
- name: Create web docker network
  docker_network:
    name: web
- name: Start traefik docker project
  docker_compose: project_src={{docker_compose_files_folder}}/traefik state=present
