---
- name: Copy traefik files
  template:
   src: "{{item}}"
   dest: "{{docker_compose_files_folder}}/traefik/{{item}}"
  loop:
    - .env
    - docker-compose.yml
    - data/traefik.toml
- name: Create web docker network
  community.general.docker_network:
    name: web
- name: Start traefik docker project
  docker_compose:
    project_src: "{{docker_compose_files_folder}}/traefik"
    state: present
