concurrent = 1
check_interval = 0

[[runners]]
  name = "local-runner"
  url = "https://gitlab.banditlair.com/"
  token = "1cc1e58b1325920f45fc52a4468292"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
