---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: latest
    cache_valid_time: 3600
  register: result
  retries: 3
  until: result is success

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Pull docker images
  docker_image: name="{{ item }}"
  with_items:
    - "k8s.gcr.io/kube-apiserver-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-controller-manager-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-proxy-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-scheduler-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/pause-{{ kube_arch }}:3.1"
    - "quay.io/coreos/flannel:{{ cni_version }}-{{ kube_arch }}"

- name: Pull etcd if not multimaster
  docker_image: name="k8s.gcr.io/etcd-{{ kube_arch }}:{{ etcd_version }}"
  when: groups.k8s_masters | length == 1
