---
- name: Create fullBackup.sh
  template:
    src: fullBackup.sh
    dest: /root/fullBackup.sh
    mode: 0700
- name: Create backup cron job
  cron:
    name: daily backup
    state: present
    minute: 0
    hour: 4
    job: "/root/fullBackup.sh >> /var/log/backup.log 2>&1"

