---
- name: Create fullBackup.sh
  template:
    src: fullBackup.sh
    dest: /root/fullBackup.sh
    mode: 0700
- name: Copy daily-backup.service
  copy:
    src: daily-backup.service
    dest: /etc/systemd/system/
    mode: 0700
- name: Copy daily-backup.timer
  copy:
    src: daily-backup.timer
    dest: /etc/systemd/system/
    mode: 0700
- name: Enable and start daily-backup
  systemd:
    name: daily-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes

