version: '2.2'

networks:
  web:
    external:
      name: web

services:
  emby:
    image: emby/embyserver:latest
    volumes:
        - ./config:/config
        - /media:/media:ro
        - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=33
      - GID=33
    labels:
      - "traefik.backend=emby"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:emby.banditlair.com"
      - "traefik.enable=true"
      - "traefik.port=8096"
      - "traefik.default.protocol=http"
    networks:
      - web
    restart: always
