---
- name: Copy plex docker files
  copy:
    src: plex
    dest: "{{docker_compose_files_folder}}"
- name: Create plex .env
  template:
    src: plex/.env
    dest: "{{docker_compose_files_folder}}/plex/.env"
- name: Start plex docker project
  docker_service:
    project_src: "{{docker_compose_files_folder}}/plex"
    state: present