version: '2.2'

networks:
  web:
    external:
      name: web

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: ${GITLAB_DOMAIN}
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.backend=gitlab"
      - "traefik.gitlab.frontend.rule=Host:gitlab.banditlair.com"
      - "traefik.gitlab.port=9090"
      - "traefik.registry.frontend.rule=Host:registry.banditlair.com"
      - "traefik.registry.port=5005"
    ports:
      - "2224:22"
    expose:
      - 9090
      - 5005
    volumes:
      - ./config:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /var/lib/gitlab:/var/opt/gitlab
      - /backups/gitlab:/var/opt/gitlab/backups
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    restart: always

  runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - ./runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
