---
- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{docker_compose_files_folder}}/invidious/"

- name: Checkout git repo
  git:
    repo: https://github.com/omarroth/invidious.git
    dest: "{{docker_compose_files_folder}}/invidious/repo"
    force: yes

- name: Build and start docker project
  docker_compose:
    project_src: "{{docker_compose_files_folder}}/invidious"
    build: yes
    pull: yes
    state: present
